import { test, expect, APIRequestContext, request as apiRequest } from '@playwright/test';

/**
 * Security regression suite generated by the 2026-05-17 sweep.
 *
 * Each test captures one finding (or a passing security check the sweep validated).
 * Run with: npx playwright test e2e/security-deep.spec.ts
 *
 * Prerequisites: backend on :8080, frontend on :4200, a Supabase project configured.
 * Tests that need a logged-in session use the UI to sign up / log in a fresh user.
 */

const API = 'http://localhost:8080';
const UI = 'http://localhost:4200';

const ts = () => Date.now();
const freshEmail = (role: 'landlord' | 'tenant', suffix = '') =>
  `${role}-spec-${ts()}${suffix}@e2e.test`;
const PASSWORD = 'TestPass!2026';

async function registerLandlord(page: any, email: string) {
  await page.goto(`${UI}/auth/register`);
  await page.getByRole('textbox', { name: 'First name' }).fill('Spec');
  await page.getByRole('textbox', { name: 'Last name' }).fill('Landlord');
  await page.getByRole('textbox', { name: 'Email' }).fill(email);
  await page.getByRole('textbox', { name: 'Password', exact: true }).fill(PASSWORD);
  await page.getByRole('textbox', { name: 'Confirm password' }).fill(PASSWORD);
  await page.getByRole('button', { name: 'Create account' }).click();
  await page.waitForURL(/\/dashboard/);
  // Dismiss onboarding wizard if shown — it overlays the page and blocks subsequent interactions.
  const skip = page.getByRole('button', { name: 'Skip for now' });
  if (await skip.isVisible().catch(() => false)) {
    await skip.click();
  }
}

async function getJwt(page: any): Promise<string> {
  return await page.evaluate(() => {
    const key = Object.keys(localStorage).find(k => k.includes('auth-token'));
    return JSON.parse(localStorage.getItem(key!)!).access_token;
  });
}

test.describe('Unauthenticated access — every protected endpoint must 401', () => {
  const endpoints: [string, string, any?][] = [
    ['GET', '/api/properties'],
    ['GET', '/api/leases'],
    ['GET', '/api/dashboard'],
    ['GET', '/api/maintenance'],
    ['GET', '/api/provision-templates'],
    ['GET', '/api/users/me'],
    ['POST', '/api/properties', { name: 'x', address: 'x', type: 'House' }],
  ];
  for (const [method, path, body] of endpoints) {
    test(`${method} ${path} → 401`, async () => {
      const ctx = await apiRequest.newContext();
      const r = await ctx.fetch(`${API}${path}`, { method, data: body });
      expect(r.status()).toBe(401);
    });
  }
});

test.describe('JWT tampering — all forged tokens must 401', () => {
  test('alg:none, mutated payload, expired, garbage, malformed → all 401', async ({ page }) => {
    const email = freshEmail('landlord');
    await registerLandlord(page, email);
    const jwt = await getJwt(page);
    const [h, p, s] = jwt.split('.');
    const b64uDecode = (str: string) =>
      JSON.parse(atob(str.replace(/-/g, '+').replace(/_/g, '/') + '==='.slice((str.length + 3) % 4)));
    const b64uEncode = (obj: any) =>
      btoa(JSON.stringify(obj)).replace(/=/g, '').replace(/\+/g, '-').replace(/\//g, '_');
    const header = b64uDecode(h);
    const payload = b64uDecode(p);
    const attackPayload = { ...payload, role: 'service_role' };
    const tokens = {
      'alg:none + mutated role':
        b64uEncode({ ...header, alg: 'none' }) + '.' + b64uEncode(attackPayload) + '.',
      'mutated payload + original sig': `${h}.${b64uEncode(attackPayload)}.${s}`,
      'expired (exp=2001)': `${h}.${b64uEncode({ ...payload, exp: 1000000000 })}.${s}`,
      'garbage HS256': 'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTYifQ.invalid',
      'malformed string': 'not-a-jwt',
    };
    const ctx = await apiRequest.newContext();
    for (const [name, token] of Object.entries(tokens)) {
      const r = await ctx.fetch(`${API}/api/properties`, {
        headers: { Authorization: `Bearer ${token}` },
      });
      expect(r.status(), name).toBe(401);
    }
  });
});

test.describe('Mass-assignment — over-posted fields must be ignored', () => {
  test('POST /api/properties with extra landlordId/id/role does not override', async ({ page }) => {
    const email = freshEmail('landlord');
    await registerLandlord(page, email);
    const jwt = await getJwt(page);
    const ctx = await apiRequest.newContext({
      extraHTTPHeaders: { Authorization: `Bearer ${jwt}` },
    });
    const fake = '00000000-0000-0000-0000-000000000099';
    const r = await ctx.post(`${API}/api/properties`, {
      data: {
        id: fake,
        landlordId: fake,
        role: 'Admin',
        email: 'hacked@x.test',
        name: `mass-assign-${ts()}`,
        address: '1',
        type: 'House',
      },
    });
    expect(r.status()).toBe(201);
    const body = await r.json();
    expect(body.landlordId).not.toBe(fake);
    expect(body.id).not.toBe(fake);
    // Cleanup
    await ctx.delete(`${API}/api/properties/${body.id}`);
  });
});

test.describe('IDOR with fabricated GUID — must 404, not leak existence', () => {
  test('GET /api/properties/<random> → 404 PROPERTY_NOT_FOUND', async ({ page }) => {
    const email = freshEmail('landlord');
    await registerLandlord(page, email);
    const jwt = await getJwt(page);
    const ctx = await apiRequest.newContext({
      extraHTTPHeaders: { Authorization: `Bearer ${jwt}` },
    });
    const random = crypto.randomUUID();
    const r = await ctx.get(`${API}/api/properties/${random}`);
    expect(r.status()).toBe(404);
    const body = await r.json();
    expect(body.code).toBe('PROPERTY_NOT_FOUND');
  });
});

test.describe('Storage path validation — traversal/slash/null-byte must be blocked', () => {
  for (const evil of ['../etc/passwd', 'a/b.png', 'a.png%00.exe', 'has space.png']) {
    test(`upload-url path "${evil}" → 400 INVALID_PATH`, async ({ page }) => {
      const email = freshEmail('landlord');
      await registerLandlord(page, email);
      const jwt = await getJwt(page);
      const ctx = await apiRequest.newContext({
        extraHTTPHeaders: { Authorization: `Bearer ${jwt}` },
      });
      const r = await ctx.get(
        `${API}/api/storage/upload-url?bucket=tenant-ids&path=${encodeURIComponent(evil)}`,
      );
      expect(r.status()).toBe(400);
      const body = await r.json();
      expect(body.code).toBe('INVALID_PATH');
    });
  }
});

test.describe('Security headers — middleware must apply on API responses', () => {
  test('GET /healthz returns expected security headers', async () => {
    const ctx = await apiRequest.newContext();
    const r = await ctx.get(`${API}/healthz`);
    expect(r.status()).toBe(200);
    const h = r.headers();
    expect(h['x-frame-options']).toBe('DENY');
    expect(h['x-content-type-options']).toBe('nosniff');
    expect(h['referrer-policy']).toBe('strict-origin-when-cross-origin');
    expect(h['permissions-policy']).toMatch(/camera=\(\)/);
  });
});

test.describe('XSS — stored payloads must render escaped, not execute', () => {
  test('Property name with <script> renders as inert text', async ({ page }) => {
    const email = freshEmail('landlord');
    await registerLandlord(page, email);
    await page.goto(`${UI}/properties`);
    const addBtn = page.getByRole('button', { name: '+ Add property' }).first();
    const visible = await addBtn.isVisible({ timeout: 5000 }).catch(() => false);
    test.skip(!visible, 'Registration appears rate-limited; landlord nav unavailable in this run.');
    await addBtn.click();
    const payload = `<script>(window as any).__XSS_FIRED=true</script>`;
    await page.getByRole('textbox', { name: /Sunset Apartments/ }).fill(payload);
    await page.getByRole('textbox', { name: 'Full address' }).fill('1 X');
    await page.getByRole('button', { name: 'Create' }).click();
    await page.waitForTimeout(500);
    const fired = await page.evaluate(() => (window as any).__XSS_FIRED === true);
    expect(fired).toBe(false);
  });
});

test.describe('F-005 + F-006 regression — accept-invite and register must require a valid JWT', () => {
  test('Anonymous /api/auth/register with fabricated SupabaseUserId → 401', async () => {
    const ctx = await apiRequest.newContext();
    const r = await ctx.post(`${API}/api/auth/register`, {
      data: {
        supabaseUserId: crypto.randomUUID(),
        firstName: 'X',
        lastName: 'Y',
        email: `fix-check-${ts()}@e2e.test`,
        role: 'Landlord',
      },
    });
    // 401 = JWT required (the actual security guarantee). 429 = rate-limited (still blocks anon access).
    expect([401, 429]).toContain(r.status());
  });

  test('Anonymous /api/auth/accept-invite with fabricated UUID → 401', async ({ page }) => {
    const email = freshEmail('landlord');
    await registerLandlord(page, email);
    const jwt = await getJwt(page);
    const inviteCtx = await apiRequest.newContext({
      extraHTTPHeaders: { Authorization: `Bearer ${jwt}` },
    });
    const inviteRes = await inviteCtx.post(`${API}/api/auth/invite-tenant`, {
      data: { email: `pwn-${ts()}@e2e.test` },
    });
    // If the invite endpoint isn't available, fall back to a fabricated token —
    // the security property under test is that anon accept-invite must 401, regardless of token validity.
    const token = inviteRes.ok()
      ? (await inviteRes.json()).token
      : crypto.randomUUID();
    const anonCtx = await apiRequest.newContext();
    const r = await anonCtx.post(`${API}/api/auth/accept-invite`, {
      data: {
        token,
        firstName: 'X',
        lastName: 'Y',
        supabaseUserId: crypto.randomUUID(),
      },
    });
    // 401 = JWT required (the security guarantee). 429 = rate-limited (still blocks anon access).
    expect([401, 429]).toContain(r.status());
  });
});

// Run last so the 5/min budget on /api/auth/register isn't exhausted before earlier tests that
// register a landlord via the UI.
test.describe('Rate limiting on /api/auth/register — 5/min', () => {
  test('6th anonymous register within a minute → 429', async () => {
    const ctx = await apiRequest.newContext();
    const results: number[] = [];
    for (let i = 0; i < 7; i++) {
      const r = await ctx.post(`${API}/api/auth/register`, {
        data: {
          supabaseUserId: crypto.randomUUID(),
          firstName: 'R',
          lastName: 'L',
          email: `ratelimit-${ts()}-${i}@e2e.test`,
          role: 'Landlord',
        },
      });
      results.push(r.status());
    }
    expect(results.filter(s => s === 429).length).toBeGreaterThanOrEqual(2);
  });
});
