// Generates src/environments/environment.ts from process.env at build time.
// Used by Vercel — the build host's env vars flow into the bundled Angular app.

const fs = require('fs');
const path = require('path');

const required = ['NG_API_URL', 'NG_SUPABASE_URL', 'NG_SUPABASE_ANON_KEY'];
const missing = required.filter(k => !process.env[k]);
if (missing.length) {
  console.error(`[set-env] Missing required env vars: ${missing.join(', ')}`);
  process.exit(1);
}

const content = `// Auto-generated by scripts/set-env.js — do not edit by hand.
export const environment = {
  production: true,
  apiUrl: ${JSON.stringify(process.env.NG_API_URL)},
  supabaseUrl: ${JSON.stringify(process.env.NG_SUPABASE_URL)},
  supabaseAnonKey: ${JSON.stringify(process.env.NG_SUPABASE_ANON_KEY)},
  stripePublishableKey: ${JSON.stringify(process.env.NG_STRIPE_PUBLISHABLE_KEY ?? '')}
};
`;

const target = path.join(__dirname, '..', 'src', 'environments', 'environment.ts');
fs.writeFileSync(target, content);
console.log(`[set-env] Wrote ${target}`);
